name: wasmi
version: 0.1.0
description: An experimental Wasm interpreter for Dart.
repository: https://github.com/devoncarew/wasmi

environment:
  sdk: ^3.3.0

dependencies:
  collection: any
  path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
