name: wasmi
version: 0.1.0
description: An experimental Wasm interpreter for Dart.
repository: https://github.com/devoncarew/wasmi

environment:
  sdk: ^3.3.0

dependencies:
  collection: any

dev_dependencies:
  code_builder: ^4.10.0
  dart_style: ^2.3.0
  lints: ^3.0.0
  meta: ^1.12.0
  path: ^1.8.0
  test: ^1.24.0
